# Generated by Django 3.0 on 2020-01-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
