# Generated by Django 3.0 on 2020-01-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createApp', '0002_auto_20200107_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
